name: Test

on:
  workflow_dispatch:

jobs:
  trigger-cypress-tests:
      name: "Trigger Cypress Tests in Separate Repository"
      runs-on: ubuntu-latest
      steps:
        - name: Trigger Cypress Tests
          run: |
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.CYPRESS_TRIGGER_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{"event_type": "run-cypress-tests", "client_payload": { "pr_number": "${{ github.event.pull_request.number }}", "branch": "${{ github.head_ref }}" }}' \
              https://api.github.com/repos/sarahligbe/kubernetes-cluster/dispatches